title: Srinithi Nivashini | M.E. CSE Portfolio
description: Master of Engineering student specializing in Machine Learning and NLP.
theme: jekyll-theme-primer
remote_theme: pages-themes/primer@v0.6.0
